[package]
name = "spotify-download"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librespot = "0.4"
clap = { version = "4.1", features = ["derive"] }
thiserror = "1.0"
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
async-stream = "0.3"
futures-util = "0.3"
