name: Check build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y build-essential libasound2-dev black
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
