name: Check build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y build-essential libasound2-dev black
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
